/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlodgasRouteImport } from './routes/blodgas'
import { Route as LugnRouteImport } from './routes/lugn'
import { Route as StewartRouteImport } from './routes/stewart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlodgasRoute = BlodgasRouteImport.update({
  id: '/blodgas',
  path: '/blodgas',
  getParentRoute: () => rootRouteImport,
} as any)
const LugnRoute = LugnRouteImport.update({
  id: '/lugn',
  path: '/lugn',
  getParentRoute: () => rootRouteImport,
} as any)
const StewartRoute = StewartRouteImport.update({
  id: '/stewart',
  path: '/stewart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blodgas': typeof BlodgasRoute
  '/lugn': typeof LugnRoute
  '/stewart': typeof StewartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blodgas': typeof BlodgasRoute
  '/lugn': typeof LugnRoute
  '/stewart': typeof StewartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blodgas': typeof BlodgasRoute
  '/lugn': typeof LugnRoute
  '/stewart': typeof StewartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blodgas' | '/lugn' | '/stewart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blodgas' | '/lugn' | '/stewart'
  id: '__root__' | '/' | '/blodgas' | '/lugn' | '/stewart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlodgasRoute: typeof BlodgasRoute
  LugnRoute: typeof LugnRoute
  StewartRoute: typeof StewartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blodgas': {
      id: '/blodgas'
      path: '/blodgas'
      fullPath: '/blodgas'
      preLoaderRoute: typeof BlodgasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugn': {
      id: '/lugn'
      path: '/lugn'
      fullPath: '/lugn'
      preLoaderRoute: typeof LugnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stewart': {
      id: '/stewart'
      path: '/stewart'
      fullPath: '/stewart'
      preLoaderRoute: typeof StewartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlodgasRoute: BlodgasRoute,
  LugnRoute: LugnRoute,
  StewartRoute: StewartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
